<?php
/**
 * Created by PhpStorm.
 * User: xywy
 * Date: 2016/6/17
 * Time: 17:00
 */

namespace app\controllers;

use app\components\base\HttpBearerAuth;
use Yii;
use yii\base\ActionEvent;
use yii\rest\ActiveController;
use app\components\helper;

class CommonController extends ActiveController
{
    public $modelClass = 'yii\db\ActiveRecord';
    public $serializer = [
        'class' => 'app\components\rest\Serializer',
        'collectionEnvelope' => 'data',
    ];
    private $result = [
        'code' => 10000,
        'message' => 'success',
        'data' => [],
    ];
    const MY_AFTER_EVENT = 'myAfterEvent';

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        return $behaviors;
    }

    public function afterAction($action, $result)
    {
        $return = parent::afterAction($action, $result); // TODO: Change the autogenerated
        $event = new ActionEvent($action);
        $event->result = $return;
        $this->trigger(self::MY_AFTER_EVENT, $event);
        if (!isset($return['data']) && $return) {
            $this->result['data'] = $return;
            return $this->result;
        }
        if (is_array($return)) {
            return array_merge($this->result, $return);

        } else {
            if (!$this->result['data']) unset($this->result['data']);
            return $this->result;
        }
    }

    public function actions()
    {
        $return = parent::actions(); // TODO: Change the autogenerated stub
        //$return=[];
        return $return;
    }

    public function httpBearerAuthExcept()
    {

        return [
            'user/user-relational/index'
        ];
    }
}