<?php
/**
 * Created by PhpStorm.
 * User: wangzhen
 * Date: 2016/7/1
 * Time: 16:42
 */

namespace app\controllers;
use app\components\base\HttpBearerAuth;
use app\components\helper;
use app\models\user\User;


class VerificationController extends CommonController
{

    public function httpBearerAuthExcept()
    {
        return [];
    }

    public function httpBearerAuthOnly()
    {
        return [];
    }

    public function beforeAction($action)
    {
        $return=parent::beforeAction($action); // TODO: Change the autogenerated stub

//        $user=User::findOne(8672223);
//        //token对应的用户与当前登录用户不匹配则提示错误
//        if(\Yii::$app->user->identity != $user)
//        {
//            throw new helper\ExceptionHelper(helper\ExceptionHelper::UserOAuth());
//        }
        return $return;
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        if(in_array(\Yii::$app->requestedAction->id,$this->httpBearerAuthExcept())){
            return $behaviors;
        }

        \Yii::$app->getUser()->identityClass='app\models\user\User';
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'except'=>$this->httpBearerAuthExcept(),
            'only'=>$this->httpBearerAuthOnly(),
        ];
        return $behaviors;
    }
}