<?php
namespace app\models;


class UserModel extends CommonModel
{
    public static function getDb()
    {
        return \YII::$app->dbdc;
    }

    /**
     * @return string 返回该AR类关联的数据表名
     */
    public static function tableName()
    {
        return 'dc_dynamic';
    }
    public function fields()
    {
        $rs=parent::fields(); // TODO: Change the autogenerated stub
        return $rs;
    }
}